---
title:
runtime: shiny
output: html_document
keep_md: yes
---

```{r engine='bash', echo=FALSE}
val=`cat quantmeasures/rest-on_data_abs_mean.rms`
echo "Mean Absolute Displacement : $val mm" 
val=`cat quantmeasures/rest-on_data_rel_mean.rms`
echo "Mean Relative Displacement : $val mm"

```

List of All Outliers (e002)
```{r engine='bash', echo=FALSE}
cat quantmeasures/rest-on_e002_outliers_volumes.txt
```

###Percentage of Motion Outlier Volumes
```{r engine='bash', echo=FALSE}
num_outliers=`cat quantmeasures/rest-on_all_outliers.txt | wc -l`
num_volumes=`fslval quantmeasures/rest-on_e002.nii.gz dim4`
percent_outliers=`echo ${num_outliers} ${num_volumes}|awk '{printf "%3.2f", $1/$2}'`
echo "${percent_outliers}%"
```
Displacement Outliers for e002
```{r engine='bash', echo=FALSE}
cat quantmeasures/rest-on_e002_fd_spike_vols
```
Displacement Outliers for Optimally Combined Time Series 
```{r engine='bash', echo=FALSE}
cat quantmeasures/rest-on_e00213_tsoc_fd_spike_vols
```
Displacement Outliers for Denoised Time Series
```{r engine='bash', echo=FALSE}
cat quantmeasures/rest-on_e00213_medn_fd_spike_vols
```

DVARS Outliers for e002
```{r engine='bash', echo=FALSE}
cat quantmeasures/rest-on_e002_dvars_spike_vols
```

DVARS Outliers for Optimally Combined Time Series
```{r engine='bash', echo=FALSE}
cat quantmeasures/rest-on_e00213_tsoc_dvars_spike_vols
```

DVARS Outliers for Denoised Time Series
```{r engine='bash', echo=FALSE}
cat quantmeasures/rest-on_e00213_medn_dvars_spike_vols
```

